<div id="homepage-tabs">
    <ul>
        <li><a href="#fragment-1"><span>What's New</span></a></li>
        <li><a href="#fragment-2"><span>Sale</span></a></li>
    </ul>
    <div id="fragment-1">
        <?= $block->getChildHtml('tab1') ?>
    </div>
    <div id="fragment-2">
        <?= $block->getChildHtml('tab2') ?>
    </div>
</div>

<script>
require([
        'jquery',
        'jquery/ui'
    ], function($, tabs) {
        $("#homepage-tabs").tabs();
    }
);
</script>
